### ISSUE TITLE
"Add" button isn't shown for association tables that refer to generated tables.

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#1111]
In RBK, I have an association table called `Schematic_Stage_Association` that references tables `Schematic` and `Developmental_Stages`. `Developmental_Stages` is marked as `generated`; the other tables aren't. If I view a record in the `Schematic` table, I would expect to see an button to add records to `Schematic_Stage_Association`, but instead all I see is `View More`. I can add records to `Schematic_Stage_Association` by typing in a `recordedit` URL.

@hongsudt thinks this might be related to #1106 and might be fixed by https://github.com/informatics-isi-edu/chaise/pull/1107/commits/943d6e2d179cfb7273b152bbdd1974a0c2e6ec98

**Comment by hongsudt** [comment]
@ljpearlman can you check whether this is still an issue?

**Comment by hongsudt** [comment]
@jrchudy This problem should already be fixed, right?

**Comment by jrchudy** [comment]
I don't think so. I don't see any reference to it from a PR that we already merged..

But if @ljpearlman could verify whether it is still an issue or not we will know 😄

**Comment by hongsudt** [comment]
@nitishksahu please investigate whether this problem still exists by following Laura's example.

**Comment by nitishksahu** [comment]
The issue is still reproducible, we do not see `Add` button to add entries to the association table when the associated table is annotated as `generated`

**Comment by nitishksahu** [comment]
I updated my previous comments, the application is working as we expect it to be.
- [Demo](https://dev.isrd.isi.edu/chaise/record/#32051/product-unordered-related-tables-links:accommodation/id=2004) -- The `association_table` is showing the associations.
- [Schema Defination](https://dev.isrd.isi.edu/ermrest/catalog/32051/schema/product-unordered-related-tables-links) -- `related_table` is marked with annotation `generated`

Assigning this to @ljpearlman to verify.
