### ISSUE TITLE
Tooltip in data-entry app

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#351]
The data-entry app should display the same tool-tips for input columns based on the column comment in the model as in the record app.

**Comment by karlcz** [comment]
Actually, I wonder if we should consider displaying the column comment alongside the column name or entry field all the time, rather than just with an on-hover tool tip...

**Comment by robes** [comment]
Personally I think it will clutter unless we make the font unreadably small. My $0.02…

**Comment by howdyjessie** [comment]
Columns that have a non-null comment now have on-hover tooltips on its column heading and is indicated by the dotted black underline. It can be viewed [here](https://dev.isrd.isi.edu/~jessie/chaise/data-entry/#1/legacy:dataset) when hovering over the "Owner" heading. The code is pushed to the [`de-column-tooltips#351`](https://github.com/informatics-isi-edu/chaise/tree/de-column-tooltips%23351) branch.

Tagging @jrchudy for code review.

**Comment by karlcz** [comment]
I just updated synapse-dev to de-column-tooltips#351 and also ermrestjs to the latest head that includes the commit you mentioned.  I still don't see the tooltips on the data-entry, though I do see them on a record page for the same table.

**Comment by howdyjessie** [comment]
@karlcz Could you pull down the latest from ermrestjs (master branch) and the latest from this feature branch ( [`de-column-tooltips#351`](https://github.com/informatics-isi-edu/chaise/tree/de-column-tooltips%23351)) again into synapse-dev? It should work now. 

It turns out the main problem was that I misspelled "commment" in ermrestjs (it had an extra `m`) while spelling "comment" correctly in Chaise.

All those red console errors earlier was Angular complaining about the periods in `RNA Conc.` and `DNA Conc.` because it couldn't tell the difference between the periods for accessing an object property and the periods in those column names. It also complained about the spaces in column names like `Birth Date`. I switched to bracket notation to fix both issues.

**Comment by karlcz** [comment]
@howdyjessie I think I updated both chaise and ermrest as you said and still don't see data-entry tooltips.

**Comment by howdyjessie** [comment]
Okay @karlcz has tested this feature; I'm assigning this to @jrchudy for code review. The latest code is pushed to the [`de-column-tooltips#351`](https://github.com/informatics-isi-edu/chaise/tree/de-column-tooltips%23351) branch. There was also an [update to ermrestjs](https://github.com/informatics-isi-edu/ermrestjs/commit/7821717a93648e3404787a977baac0a12cccb8ea) on the master branch.

**Comment by jrchudy** [comment]
I pulled this code and tested it in my own user directory on dev isrd. The changes look non intrusive and I verified that the tooltip shows up and the dotting line shows up to note there is a tooltip there.
