### ISSUE TITLE
search: 409 conflict when faceting a timestamp or timestamptz column

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#545]
ERROR: 409
I got the following error message when I tried to facet based on a timestamp or timestamptz column. Please fix. 

```
ResponseText: 409 Conflict
The request conflicts with the state of the server. invalid input syntax for type timestamp: "Invalid Date"
LINE 8: WHERE ((t0."Creation_Timestamp" >= 'Invalid Date'::timestamp...
^

TextStatus: error
ErrorThrown: Conflict
URL: https://dev.gpcrconsortium.org/ermrest/catalog/1/aggregate/A:=experiments:Experiment/Creation_Timestamp::geq::Invalid%20Date/$A/cnt:=cnt_d(Name)
```

**Comment by svoinea** [comment]
@hongsudt In order to debug, please provide details where does it happen and the scenario used.

**Comment by hongsudt** [comment]
This is on dev@gpcr. Experiment table has a creation_timestamp which is defined as a timestamptz. I hid it from faceting but you could undo this to debug.

**Comment by svoinea** [comment]
@hongsudt I have unhidden the column. The error as described above can not be recreated.

Looking at the table, it has 4 rows. There is a row having the NULL value for the `Creation_Timestamp` column; all the others have the same value `2016-08-22 21:25:38.479892-07`.

I have detected based on this example, that for timestamps, as they are cast to dates, the maximum value needs to be incremented with 1 day.
Otherwise, the search results will not contain the records having the maximum value of the date.
I have fixed it through the commit 1ca259b9955d4a2d2913877ed9d8fe32e335ee6a. Anyway, that's something independent of the above mentioned bug.

Looks to me that somehow (?), the date widget had an error, and as a result, it was generating the "Invalid Date" value.

**Comment by hongsudt** [comment]
@akumar03 can you please review this fix.

**Comment by akumar03** [comment]
Still see the error on dev: 
https://dev.gpcrconsortium.org/chaise/search/#1/experiments:SOP?facets=(SOP:Last_Modified::geq::Invalid Date/SOP:Last_Modified::leq::Invalid Date)&layout=table&page=1

ResponseText: 409 Conflict
The request conflicts with the state of the server. invalid input syntax for type timestamp with time zone: "Invalid Date"
LINE 8: WHERE ((t0."Last_Modified" >= 'Invalid Date'::timestamptz))
^

TextStatus: error
ErrorThrown: Conflict
URL: https://dev.gpcrconsortium.org/ermrest/catalog/1/aggregate/A:=experiments:SOP/Last_Modified::geq::Invalid%20Date/$A/cnt_Title:=cnt(Title),cnt_Procedure:=cnt(Procedure)

**Comment by hongsudt** [comment]
@svoinea I am moving this to this week.

**Comment by hongsudt** [comment]
This is still a problem.. None of the timestamp seems to work. Please fix this asap. 

https://demo2.gpcrconsortium.org/chaise/search/#1/experiments:experiment?facets=(experiment:last_modified_timestamp::geq::Invalid%20Date/experiment:last_modified_timestamp::leq::Invalid%20Date)&layout=table&page=1

**Comment by svoinea** [comment]
Should be fixed now through the commit ee92efe07c744d0aab507a37db3f9959673986e6 in the `chaise` repository.
Currently testing can be performed using the https://dev.gpcrconsortium.org/~serban/chaise/search/#1/experiments:experiment link.

**Comment by hongsudt** [comment]
When the issue is ready to be reviewed, please move it to the review column and assign the reviewer.

**Comment by hongsudt** [comment]
It is not working on gpcr-dev. It no longer throws an error, but all the dates are greyed out except Nov 3 and 4. And when I selected a date, no filtering was applied.

**Comment by hongsudt** [comment]
@svoinea Your commit doesn't fix the problem.. See my previous comment.

**Comment by svoinea** [comment]
I don't understand which are the expectations.
All the entries have a single date: `November 3`.
What filter do you want to apply? If in the `From:` widget` you select 'November 4, you get zero results (because none of the timestamps is equal to `November 4`).
Same thing happens when you select in the `To:` widget `November 3`.

**Comment by hongsudt** [comment]
I should be able to select an arbitrary begin date and end date and apply
that as a filter..

For example, I should be able to ask for everything from 10/15 to 11/31 and
that shouldn't fail.
