### ISSUE TITLE
E2E Testing Problem with Angular Router

### ISSUE THREAD

**Issue by shinyichen** [informatics-isi-edu/chaise#582]
In testing the Recordset app, after the page was loaded, the page was rerouted with the addition of slash `/` after the hash `#`. So the original url `https://dev.isrd.isi.edu/~jchen/chaise/recordset/#1/legacy:dataset` becomes `https://dev.isrd.isi.edu/~jchen/chaise/recordset/#/1/legacy:dataset`. The app complains because now the URL is invalid. I remove the code (see #581) which reloads the page when address bar changes, this made the test run through.

Possibly that protractor is trying to use angular-router to navigate in the tests and causes the `/` to be added. Further investigation is needed.

**Comment by hongsudt** [comment]
This problem has been solved..

**Comment by hongsudt** [comment]
@jrchudy @howdyjessie @chiragsanghvi @robes Is this still an issue?

**Comment by robes** [comment]
I am not knowledgable about this issue.

**Comment by jrchudy** [comment]
This is still an issue in cases where we want to set `ignoreSynchronization` to `false`, based on my previous comment.

But it appears that there is another way that we can imitate features that rely on waiting for a response. We can use a mock object framework for testing the server responses and force those to be delayed to test specific functionality. I believe `nock` allows for this and we already use it in `ermrestJS`.

**Comment by hongsudt** [comment]
This issue is so old now.. I am going to close it..
